version: "3.9"

# Development overrides: live-reload frontend, exposed ports for debugging
services:
  triplestore:
    ports:
      - "8890:8890"

  validation:
    ports:
      - "5000:80"
    environment:
      FLASK_DEBUG: "1"
      BASE_REPORT_URL: "http://localhost/reports"

  identifier:
    ports:
      - "80:80"
