(define-resource validation-job ()
  :class (s-prefix "ext:ValidationJob")
  :properties `((:source-url     :string   ,(s-prefix "ext:sourceUrl"))
                (:status         :string   ,(s-prefix "ext:status"))
                (:endpoint-type  :string   ,(s-prefix "ext:endpointType"))
                (:created-at     :datetime ,(s-prefix "dct:created"))
                (:started-at     :datetime ,(s-prefix "ext:startedAt"))
                (:finished-at    :datetime ,(s-prefix "ext:finishedAt"))
                (:error-message  :string   ,(s-prefix "ext:errorMessage"))
                (:report-url     :string   ,(s-prefix "ext:reportUrl"))
                (:graph-uri      :string   ,(s-prefix "ext:graphUri")))
  :resource-base (s-url "http://mu.semte.ch/resources/validation-jobs/")
  :on-path "jobs")
